# Generated by Django 6.0.2 on 2026-03-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryMovement',
        ),
    ]
