# Generated by Django 6.0.2 on 2026-03-18 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_delete_inventorymovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMenagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quentity', models.PositiveIntegerField(default=0, help_text='Available stock quantity')),
                ('old_stock', models.PositiveIntegerField(default=0, help_text='Old stock Info.')),
                ('new_stock', models.PositiveIntegerField(default=0, help_text='New Stock Info.')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock out'), ('ADJ', 'Adjustment')], max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Optional explanation for stock change.', verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoentory_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.productmodel')),
            ],
        ),
    ]
